const PDFDocument = require('pdfkit');

const COLORS = {
  primary: '#4f46e5',
  primaryLight: '#eef2ff',
  green: '#059669',
  greenLight: '#ecfdf5',
  red: '#dc2626',
  redLight: '#fef2f2',
  dark: '#111827',
  gray: '#4b5563',
  lightGray: '#9ca3af',
  border: '#e5e7eb',
};

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4 width in points
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;

function generateResumeReportPDF(resume, analysis, res) {
  const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="Resume_Analysis_${(resume.title || 'Report').replace(/[^a-z0-9]/gi, '_')}.pdf"`
  );

  doc.pipe(res);

  let y = drawHeader(doc, resume);
  y = drawScoreBoxes(doc, analysis, y);

  if (analysis.summary) {
    y = drawSummary(doc, analysis.summary, y);
  }

  y = ensureSpace(doc, y, 60);
  y = drawTagSection(doc, 'Skills Detected', analysis.skills, y, {
    bg: COLORS.primaryLight,
    fg: COLORS.primary,
    format: (s) => (typeof s === 'string' ? s : s.name),
  });

  y = drawCardSection(doc, 'Experience', analysis.experience, y, (e) => ({
    title: e.title || 'Role',
    subtitle: [e.company, e.duration].filter(Boolean).join('  •  '),
    body: e.description,
  }));

  y = drawCardSection(doc, 'Education', analysis.education, y, (e) => ({
    title: e.degree || 'Degree',
    subtitle: [e.institution, e.year].filter(Boolean).join('  •  '),
    body: null,
  }));

  y = ensureSpace(doc, y, 60);
  y = drawTagSection(doc, 'Missing Keywords', analysis.missingKeywords, y, {
    bg: COLORS.redLight,
    fg: COLORS.red,
    format: (k) => k,
  });

  y = drawNumberedList(doc, 'Suggestions for Improvement', analysis.suggestions, y);

  drawFooter(doc, y);

  doc.end();
}

function drawHeader(doc, resume) {
  doc.rect(0, 0, doc.page.width, 100).fill(COLORS.primary);

  doc.circle(70, 50, 20).fill('#ffffff');
  doc.fillColor(COLORS.primary).font('Helvetica-Bold').fontSize(14).text('CP', 58, 43);

  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(22).text('Resume Analysis Report', 100, 28);
  doc.font('Helvetica').fontSize(10).fillColor('#e0e7ff')
    .text(`Generated by CareerPilot AI  •  ${new Date().toLocaleDateString()}`, 100, 56);

  let y = 125;
  doc.fillColor(COLORS.dark).font('Helvetica-Bold').fontSize(15).text(resume.title || 'Untitled Resume', PAGE_MARGIN, y);

  return y + 35;
}

function scoreLabel(score) {
  if (score >= 85) return 'Excellent';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Fair';
  return 'Needs Work';
}

function drawScoreBoxes(doc, analysis, y) {
  const overallScore = analysis.overallScore ?? analysis.score ?? 0;
  const atsScore = analysis.atsScore ?? 0;
  const boxWidth = (CONTENT_WIDTH - 15) / 2;
  const boxHeight = 80;

  const boxes = [
    { x: PAGE_MARGIN, score: overallScore, label: 'Overall Score', bg: COLORS.primaryLight, fg: COLORS.primary },
    { x: PAGE_MARGIN + boxWidth + 15, score: atsScore, label: 'ATS Score', bg: COLORS.greenLight, fg: COLORS.green },
  ];

  boxes.forEach((b) => {
    doc.roundedRect(b.x, y, boxWidth, boxHeight, 10).fill(b.bg);
    doc.fillColor(b.fg).font('Helvetica-Bold').fontSize(30).text(`${b.score}`, b.x, y + 14, { width: boxWidth, align: 'center' });
    doc.fillColor(COLORS.gray).font('Helvetica').fontSize(10).text(b.label, b.x, y + 48, { width: boxWidth, align: 'center' });
    doc.fillColor(b.fg).font('Helvetica-Bold').fontSize(9).text(scoreLabel(b.score), b.x, y + 62, { width: boxWidth, align: 'center' });
  });

  return y + boxHeight + 30;
}

function drawSummary(doc, summary, y) {
  y = ensureSpace(doc, y, 60);
  doc.roundedRect(PAGE_MARGIN, y, CONTENT_WIDTH, 4, 2).fill(COLORS.primary);
  y += 14;
  doc.fillColor(COLORS.dark).font('Helvetica-Bold').fontSize(13).text('Summary', PAGE_MARGIN, y);
  y += 20;
  doc.fillColor(COLORS.gray).font('Helvetica-Oblique').fontSize(10).text(summary, PAGE_MARGIN, y, { width: CONTENT_WIDTH, lineGap: 3 });
  return doc.y + 25;
}

function sectionTitle(doc, title, y) {
  doc.fillColor(COLORS.dark).font('Helvetica-Bold').fontSize(13).text(title, PAGE_MARGIN, y);
  doc.moveTo(PAGE_MARGIN, y + 18).lineTo(PAGE_MARGIN + CONTENT_WIDTH, y + 18).strokeColor(COLORS.border).lineWidth(1).stroke();
  return y + 28;
}

function drawTagSection(doc, title, items, y, { bg, fg, format }) {
  if (!items || items.length === 0) return y;

  y = ensureSpace(doc, y, 70);
  y = sectionTitle(doc, title, y);

  const paddingX = 10;
  const paddingY = 6;
  const gap = 8;
  const lineHeight = 22;
  let x = PAGE_MARGIN;

  doc.font('Helvetica').fontSize(9);

  items.forEach((raw) => {
    const text = format(raw);
    const textWidth = doc.widthOfString(text);
    const tagWidth = textWidth + paddingX * 2;

    if (x + tagWidth > PAGE_MARGIN + CONTENT_WIDTH) {
      x = PAGE_MARGIN;
      y += lineHeight + gap;
    }
    y = ensureSpace(doc, y, lineHeight + gap);

    doc.roundedRect(x, y, tagWidth, lineHeight, 11).fill(bg);
    doc.fillColor(fg).text(text, x + paddingX, y + paddingY);

    x += tagWidth + gap;
  });

  return y + lineHeight + 25;
}

function drawCardSection(doc, title, items, y, mapItem) {
  if (!items || items.length === 0) return y;

  y = ensureSpace(doc, y, 70);
  y = sectionTitle(doc, title, y);

  items.forEach((raw) => {
    const item = mapItem(raw);
    y = ensureSpace(doc, y, 55);

    const startY = y;
    doc.fillColor(COLORS.dark).font('Helvetica-Bold').fontSize(11).text(item.title, PAGE_MARGIN + 14, y, { width: CONTENT_WIDTH - 14 });
    y = doc.y + 2;

    if (item.subtitle) {
      doc.fillColor(COLORS.gray).font('Helvetica').fontSize(9).text(item.subtitle, PAGE_MARGIN + 14, y, { width: CONTENT_WIDTH - 14 });
      y = doc.y + 4;
    }

    if (item.body) {
      doc.fillColor(COLORS.gray).font('Helvetica').fontSize(9).text(item.body, PAGE_MARGIN + 14, y, { width: CONTENT_WIDTH - 14, lineGap: 2 });
      y = doc.y;
    }

    doc.moveTo(PAGE_MARGIN, startY).lineTo(PAGE_MARGIN, y).strokeColor(COLORS.primary).lineWidth(3).stroke();

    y += 16;
  });

  return y + 10;
}

function drawNumberedList(doc, title, items, y) {
  if (!items || items.length === 0) return y;

  y = ensureSpace(doc, y, 70);
  y = sectionTitle(doc, title, y);

  items.forEach((text, i) => {
    y = ensureSpace(doc, y, 30);
    const circleR = 8;
    const circleX = PAGE_MARGIN + circleR;
    const circleY = y + circleR - 1;

    doc.circle(circleX, circleY, circleR).fill(COLORS.primary);
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8).text(`${i + 1}`, circleX - 4, circleY - 4);

    doc.fillColor(COLORS.gray).font('Helvetica').fontSize(10).text(text, PAGE_MARGIN + circleR * 2 + 8, y, {
      width: CONTENT_WIDTH - circleR * 2 - 8,
      lineGap: 2,
    });
    y = doc.y + 10;
  });

  return y + 15;
}

function ensureSpace(doc, y, needed) {
  if (y + needed > 760) {
    doc.addPage();
    return PAGE_MARGIN;
  }
  return y;
}

function drawFooter(doc, y) {
  const footerY = Math.min(y + 20, doc.page.height - 45);
  doc.fillColor(COLORS.lightGray).font('Helvetica').fontSize(8).text(
    'Generated automatically by CareerPilot AI. Scores are AI estimates, not guarantees.',
    PAGE_MARGIN,
    footerY,
    { width: CONTENT_WIDTH, align: 'center' }
  );
}

module.exports = { generateResumeReportPDF };